spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    # 连接超时时间
    timeout: 10000
    jedis:
      pool:
        # 最大连接数
        max-active: 8
        # 最大阻塞等待时间(负数表示没限制)
        max-wait: 100000
        # 最大空闲
        max-idle: 10
        # 最小空闲
        min-idle: 0
logging:
  config: classpath:logback-spring.xml