# server
server:
  port: 8081
  servlet:
    context-path: /simple/auth
  tomcat:
    uri-encoding: UTF-8

#spring
spring:
  application:
    name: SimpleAuth
  cloud:
    nacos:
      config:
        group: DEV_AUTH
        # nacos配置发现地址
        server-addr: 127.0.0.1:8848
        # 对应命名空间id
        namespace: 6d17dfa1-5036-4de1-a680-c5d0bcee1a04
        # 文件格式
        file-extension: yaml
      discovery:
        # 分组名称
        group: DEV_AUTH
        # nacos服务发现地址
        server-addr: 127.0.0.1:8848
        # 对应命名空间id
        namespace: 6d17dfa1-5036-4de1-a680-c5d0bcee1a04