# servlet
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2048MB
      max-request-size: 2048MB
      location: G://tomcat/temp/file
  # datasource
  datasource:
    # 驱动配置信息
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver

    # 连接池的配置信息
    # 配置监控统计拦截的filters,去掉后监控页面sql将无法统计,'wall'用于防火墙
    filters: stat,wall,log4j
    # 最大活跃数
    maxActive: 20
    # 初始化数量
    initialSize: 1
    # 最大连接等待超时时间
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select version()
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 是否缓存preparedStatement,也就是PSCache
    # poolPreparedStatements: true
    # 打开PSCache,并指定每个连接PSCache大小,当大于0时,poolPreparedStatements自动触发修改为true
    maxOpenPreparedStatements: 20
# log
logging:
  config: classpath:logback-spring.xml

# mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
